name: pm25_components_randall
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - netcdf4
  - xarray
  - rasterio
  - rasterstats
  - geopandas
  - pyarrow
  - pip
  - pip:
    - requests
    - wget
    - hydra-core
    - snakemake
    - selenium
    - chromedriver-binary
    - tqdm
