name: satellite_pm25_raster2polygon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - netcdf4=1.6.5
  - xarray=2023.12.0
  - rasterio=1.3.9
  - rasterstats=0.19.0
  - geopandas=0.14.2
  - pyarrow=14.0.2
  - pip=23.3.2
  - pip:
    - requests==2.31.0
    - wget==3.2
    - hydra-core==1.3.2
    - snakemake==8.1.2
    - selenium==4.29.0
    - chromedriver-binary==135.0.7030.0.0
    - tqdm==4.67.1
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
