name: satellite_pm25_raster2polygon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - netcdf4=1.6.2  
  - xarray=2023.12.0
  - rasterio=1.2.10
  - rasterstats=0.19.0
  - geopandas=0.9.0
  - pyarrow=11.0.0
  - pip=23.1.2
  - pip:
    - requests==2.31.0
    - hydra-core==1.2.0
    - snakemake==8.1.2
    - selenium==4.16.0
    - webdriver_manager==4.0.1
    - wget==3
