name: satellite_pm25_raster2polygon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - netcdf4=1.6.5
  - xarray=2023.12.0
  - rasterio=1.3.9
  - rasterstats=0.19.0
  - geopandas=0.14.2
  - pyarrow=14.0.2
  - python-chromedriver-binary=123.0.6265.0.0
  - pip=23.3.2
  - pip:
    - requests==2.31.0
    - hydra-core==1.3.2
    - snakemake==8.1.2
    - selenium==4.16.0
    - webdriver_manager==4.0.1
    - wget==3.2
    - tqdm
