name: satellite_pm25_raster2polygon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - netcdf4  
  - xarray
  - rasterio
  - rasterstats
  - geopandas
  - pyarrow
  - pip
  - pip:
    - requests
    - hydra-core
    - snakemake==8.1.2
    - selenium
    - webdriver_manager
    - wget
