defaults:
  - _self_
  - datapaths: cannon_datapaths
  - shapefiles: shapefiles
  - satellite_pm25: us_pm25

# == aggregation args
temporal_freq: yearly # yearly, monthly to be matched with cfg.satellite_pm25
year: 2020

# == shapefile download args
polygon_name: zcta # zcta, county to be matched with cfg.shapefiles
shapefile_year: 2020 #to be matched with cfg.shapefiles

show_progress: false
plot_output: false  # plotting increases runtime, only use for debugging

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    