defaults:
  - _self_
  - datapaths: datapaths
  - shapefiles: zcta # zcta, county
  - satellite_pm25: annual  # annual, monthly

year: 2018
shapefile_year: 2020 #to be matched with cfg.shapefiles
shapefile_polygon_name: cb_zcta #to be matched with cfg.shapefiles

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}