defaults:
  - _self_
  - datapaths: datapaths
  - shapefiles: county # zcta, county
  - satellite_pm25: monthly  # annual, monthly

year: 2011
month: "01" # ignored if annual
shapefile_year: 2011 #to be matched with cfg.shapefiles
shapefile_polygon_name: cb_county #to be matched with cfg.shapefiles

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}