defaults:
  - _self_
  - datapaths: datapaths
  - shapefiles: shapefiles
  - satellite_pm25: satellite_pm25

# == aggregation args
temporal_freq: annual # annual, monthly to be matched with cfg.satellite_pm25
year: 2020

# == shapefile download args
polygon_name: county # zcta, county to be matched with cfg.shapefiles
shapefile_year: 2020 #to be matched with cfg.shapefiles

# == satellite pm25 download args
download_path: "~/Downloads"
download_wait_time: 5 #seconds

show_progress: false
plot_output: false  # plotting increases runtime, only use for debugging

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    